services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config 
  
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - mosquitto
    volumes:
      - ./data:/app/data
      - ./dashboard/containers.json:/app/dashboard/containers.json

  simulator:
    build: ./tools
    depends_on:
    - mosquitto
    volumes:
    - ./dashboard/containers.json:/app/dashboard/containers.json